### PR TITLE
Fix time_zones using with_tz()

### PR DESCRIPTION
**Pull request by paocorrales**
I've just realised that the issue is now close. But I check the code and I think you need to use `with_tz()` instead of `force_tz()`. 

The `force_tz()` function chances the moment in time while the clock time is the same. But you need the _same_ moment in time expressed in a different time zone. The idea is that `with_tz()` answer the question: If it's 3 PM here, what time is it in ...?

So, I added the `tz = "US/Eastern` argument so the tz is correctly defined from the beginning (the default is "UTC") and changed `with_tz()` instead of `force_tz()` when needed. 

Hope that this helps!

(Associated to issue #1 )

### CODE REVIEW

**Comment by spcanelon** [comment]
Thank you @paocorrales! I appreciate you clarifying the distinction between `with_tz()` and `force_tz()`, and setting the timezone from the start makes a lot of sense 😄

**Comment by paocorrales** [comment]
Sorry, It's me again. I kept thinking about this because I noticed that
Natalia's solution also works.

I believe is because when you create the date time using ymd_hm(), that
date is in EST and R interpret that it's in UTC. Then when the force_tz is
used to force the variable to EST, ir changes the tz but the date time it's
the same.

So, two ways to do the same! I learned a lot :)

**Comment by spcanelon** [comment]
Ahh, I see -- yes, another great example of there being multiple ways to solve a problem. Thank you for sharing this! I'm lucky to have had you and @nmorandeira making such helpful contributions!

FYI you are both listed as authors in the R notebook linked in the description of the repo 😃: https://spcanelon.github.io/rstudio-global-2021-calendar/rstudio-global-2021-schedule.nb.html
image

**Comment by nmorandeira** [comment]
great @paocorrales ! Thanks for explaining the differences between force_tz and with_tz

**Pull request merged**
